name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEAT]: "
assignees: yoanm
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: checkboxes
    id: is-related-to-problem
    attributes:
      label: Is your feature request related to a problem ?
      options:
        - label: Yes

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
