name: Dependabot PRs
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    name: ".github"
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'yoanm/.github'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-dependabot-PRs-manager.yml
