name: GitHub action release manager

on:
  workflow_call:
    inputs:
      update-inner-releases:
        description: See `yoanm/gha-versioning` `update-inner-releases` option
        required: false
        type: boolean

jobs:
  tag:
    name: Publish vX and vX.Y tags
    if: ${{ startsWith(github.repository, 'yoanm/') && github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push new tags !
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Generate vX and vX.Y tags
        uses: yoanm/gha-versioning@v1
        with:
          update-inner-releases: ${{ inputs.update-inner-releases }}
