name: Coverage upload manager

on:
  workflow_call:
    inputs:
      artifacts-pattern:
        description: Pattern used to download artifacts containing coverage data
        required: true
        type: string
      with-codacy:
        description: Whether to upload coverage data to Codacy
        required: true
        type: boolean
      with-codecov:
        description: Whether to upload coverage data to Codecov
        required: true
        type: boolean
    secrets:
      CODACY_PROJECT_TOKEN:
        required: false # But actually required if `with-codacy` is enabled !
      CODECOV_TOKEN:
        required: false # But actually required if `with-codecov` is enabled !

permissions:
  contents: read
  checks: write # For the check run creation !

jobs:
  fetch-info:
    name: Fetch triggering workflow metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # For the check run creation !
    steps:
      - name: 'Check run ○'
        uses: yoanm/temp-reports-group-workspace/utils/attach-check-run-to-triggering-workflow@v0
        with:
          name: 'Fetch triggering workflow metadata'
          fails-on-triggering-workflow-failure: true

      - uses: yoanm/temp-reports-group-workspace/utils/fetch-workflow-metadata@v0
        id: fetch-workflow-metadata

    outputs:
      commit-sha: ${{ steps.fetch-workflow-metadata.outputs.commit-sha }}
      run-id: ${{ steps.fetch-workflow-metadata.outputs.run-id }}
      branch: ${{ steps.fetch-workflow-metadata.outputs.branch }}
      pull-request: ${{ steps.fetch-workflow-metadata.outputs.pull-request }}

  codacy-uploader:
    name: Codacy
    needs: [fetch-info]
    if: ${{ inputs.with-codacy }}
    uses: yoanm/temp-reports-group-workspace/.github/workflows/codacy-upload-from-artifacts.yml@v0
    permissions:
      contents: read
      checks: write # For the check run creation !
    secrets:
      PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    with:
      artifacts-pattern: ${{ inputs.artifacts-pattern }}
      run-id: ${{ needs.fetch-info.outputs.run-id }}
      force-git-commit: ${{ needs.fetch-info.outputs.commit-sha }}
      # force-uploader-language: ...
      # force-uploader-coverage-parser: ...
      # force-uploader-cli-version: ...

  codecov-uploader:
    name: Codecov
    needs: [fetch-info]
    if: ${{ inputs.with-codecov }}
    uses: yoanm/temp-reports-group-workspace/.github/workflows/codecov-upload-from-artifacts.yml@v0
    permissions:
      contents: read
      checks: write # For the check run creation !
    secrets:
      TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      artifacts-pattern: ${{ inputs.artifacts-pattern }}
      run-id: ${{ needs.fetch-info.outputs.run-id }}
      force-git-commit: ${{ needs.fetch-info.outputs.commit-sha }}
      force-git-branch: ${{ needs.fetch-info.outputs.branch }}
      force-gh-pr: ${{ needs.fetch-info.outputs.pull-request }}
      force-uploader-build: ${{ needs.fetch-info.outputs.run-id }}
      force-uploader-build-url: ${{ needs.fetch-info.outputs.run-url }}
